# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='friends',
        ),
        migrations.AddField(
            model_name='trip',
            name='joined',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined', to='login_registration.User'),
        ),
    ]
