# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
        ('travel_buddy', '0002_auto_20170627_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='joined',
        ),
        migrations.AddField(
            model_name='trip',
            name='joined',
            field=models.ManyToManyField(related_name='joined', to='login_registration.User'),
        ),
    ]
